### ISSUE TITLE
The procedure entry point could not be located

### ISSUE THREAD

**Issue by AndreasWeste** [Dateranoth/ConanExilesServerUtility#27]
Hello, i get a messagebox from the ConanServer exe, when i start the server utility. it pops up **two** times and blocks the start of the server. Tested on two different systems: win10 and win server 2008. steam client is running in the background:

https://dl.dropboxusercontent.com/u/6588653/conenserverproblem.png

my config:
[Use MULTIHOME to Bind IP? Disable if having connection issues (yes/no)]
BindIP=yes
[Game Server IP]
ListenIP=xxx.xxx.xxx.xxx
[Game Server Port]
GamePort=7777
[Steam Query Port]
QueryPort=27015
[Server Name]
ServerName=Bandis Testserver - Do what you want
[Server Password]
ServerPass=
[Admin Password]
AdminPass=mysecretpassnobodyfindsout
[Max Players]
MaxPlayers=70
[Server Directory. NO TRAILING SLASH]
serverdir=N:\Dateranoth\ConanServer
[Use SteamCMD To Update Server? yes/no]
UseSteamCMD=yes
[SteamCMD Directory. NO TRAILING SLASH]
steamcmddir=N:\Dateranoth\SteamCMD
[Validate Files Every Time SteamCMD Runs? yes/no]
validategame=no
[Use Remote Restart ?yes/no]
UseRemoteRestart=yes
[Remote Restart Port]
ListenPort=57520
[Remote Restart Password]
RestartCode=geheim
[Hide Passwords in Log? yes/no]
ObfuscatePass=yes
[Restart Server Daily? yes/no]
RestartDaily=no
[Check for Update Every X Minutes? yes/no]
CheckForUpdate=yes
[Update Check Interval in Minutes 05-59]
UpdateInterval=05
[Daily Restart Hours? 00-23]
HotHour1=00
HotHour2=00
HotHour3=00
HotHour4=00
HotHour5=00
HotHour6=00
[Daily Restart Minute? 00-59]
HotMin=01
[Excessive Memory Amount?]
ExMem=6000000000
[Restart On Excessive Memory Use? yes/no]
ExMemRestart=yes
[Running Server with Steam Open? (yes/no)]
SteamFix=yes
[Rotate X Number of Logs every X Hours? yes/no]
logRotate=yes
logQuantity=10
logHoursBetweenRotate=24
[Use Discord Bot to Send Message Before Restart? yes/no]
UseDiscordBot=no
DiscordWebHookURL=https://discordapp.com/api/webhooks/XXXXXX/XXXX <- NO TRAILING SLASH AND USE FULL URL FROM WEBHOOK URL ON DISCORD
DiscordBotName=Conan Exiles Discord Bot
DiscordBotUseTTS=yes
DiscordBotAvatarLink=
DiscordBotTimeBeforeRestart=5
[Use Twitch Bot to Send Message Before Restart? yes/no]
UseTwitchBot=no
TwitchNick=twitchbotusername
ChatOAuth=oauth:1234 (Generate OAuth Token Here: https://twitchapps.com/tmi)
TwitchChannels=channel1,channel2,channel3
TwitchBotTimeBeforeRestart=5

**Comment by Dateranoth** [comment]
@hmmhAndreas 
`SteamFix=yes` should automatically close those windows.  Could you post your log?

**Comment by AndreasWeste** [comment]
Thank you. Interestingly, after restarting everything i cannot reproduce the problem anymore, the error messages are closing properly. I will inform you if the problem comes back. Here is my log anyway:

2017/02/19 12:59:27 Log Files Rotated
2017/02/19 13:03:22 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 13:03:31 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 13:08:32 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 13:08:40 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 13:13:40 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 13:13:48 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 13:18:48 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 13:18:57 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 13:23:57 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 13:24:05 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 13:29:06 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 13:29:14 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 13:34:14 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 13:34:24 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 13:39:25 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 13:39:34 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 13:44:35 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 13:44:44 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 13:49:45 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 13:49:55 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 13:54:56 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 13:55:05 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 14:00:06 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 14:00:15 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 14:05:16 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 14:05:26 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 14:10:27 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 14:10:36 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 14:15:36 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 14:15:43 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 14:20:43 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 14:20:51 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 14:25:51 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 14:25:58 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 14:30:59 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 14:31:06 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 14:36:06 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 14:36:13 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 14:41:13 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 14:41:22 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 14:46:22 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 14:46:29 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 14:51:29 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 14:51:37 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 14:56:38 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 14:56:45 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 15:01:45 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 15:01:52 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 15:06:53 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 15:07:04 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 15:12:04 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 15:12:11 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 15:17:11 [Bandis Testserver - Do what you want (PID: 8380)] Update Check Starting.
2017/02/19 15:17:19 [Bandis Testserver - Do what you want (PID: 8380)] Server is Up to Date. Version: 1640770
2017/02/19 15:18:32 Running SteamCMD without validate. [steamcmd.exe +@ShutdownOnFailedCommand 1 +@NoPromptForPassword 1 +login anonymous +force_install_dir N:\Dateranoth\ConanServer +app_update 443030 +quit]
2017/02/19 15:18:37 [Bandis Testserver - Do what you want (PID: 10492)] Started [ConanSandboxServer-Win64-Test.exe ConanSandBox -MULTIHOME=127.0.0.1 -Port=7777 -QueryPort=27015 -MaxPlayers=70 -AdminPassword=*** -ServerPassword= -ServerName="Bandis Testserver - Do what you want" -listen -nosteamclient -game -server -log]
2017/02/19 15:18:39 [Bandis Testserver - Do what you want (PID: 10492)] Window Handle Found: 0x000000000007080A
2017/02/19 15:23:52 [Bandis Testserver - Do what you want (PID: 10492)] Server Shutdown - Intiated by User when closing ConanServerUtility Script
2017/02/19 15:23:52 [Bandis Testserver - Do what you want (PID: 10492)] Server Window Found - Sending Ctrl+C for Clean Shutdown
2017/02/19 15:23:58 ConanServerUtility Stopped by User
2017/02/19 16:26:24 ConanServerUtility Script V2.9.1 Started
2017/02/19 16:26:24 Remote Restart Enabled. Listening for Restart Request at 127.0.0.1:57520
2017/02/19 16:26:24 Running SteamCMD without validate. [steamcmd.exe +@ShutdownOnFailedCommand 1 +@NoPromptForPassword 1 +login anonymous +force_install_dir N:\Dateranoth\ConanServer +app_update 443030 +quit]
2017/02/19 16:26:30 [Bandis Testserver - Do what you want (PID: 15888)] Started [ConanSandboxServer-Win64-Test.exe ConanSandBox -MULTIHOME=127.0.0.1 -Port=7777 -QueryPort=27015 -MaxPlayers=70 -AdminPassword=*** -ServerPassword= -ServerName="Bandis Testserver - Do what you want" -listen -nosteamclient -game -server -log]
2017/02/19 16:41:39 [Bandis Testserver - Do what you want (PID: 15888)] Server Shutdown - Intiated by User when closing ConanServerUtility Script
2017/02/19 16:41:39 [Bandis Testserver - Do what you want (PID: 15888)] Server Window Found - Sending Ctrl+C for Clean Shutdown
2017/02/19 16:42:41 ConanServerUtility Script V2.9.1 Started
2017/02/19 16:42:41 Remote Restart Enabled. Listening for Restart Request at 127.0.0.1:57520
2017/02/19 16:42:42 Running SteamCMD without validate. [steamcmd.exe +@ShutdownOnFailedCommand 1 +@NoPromptForPassword 1 +login anonymous +force_install_dir N:\Dateranoth\ConanServer +app_update 443030 +quit]
2017/02/19 16:42:50 [Bandis Testserver - Do what you want (PID: 9708)] Started [ConanSandboxServer-Win64-Test.exe ConanSandBox -MULTIHOME=127.0.0.1 -Port=7777 -QueryPort=27015 -MaxPlayers=70 -AdminPassword=*** -ServerPassword= -ServerName="Bandis Testserver - Do what you want" -listen -nosteamclient -game -server -log]
2017/02/19 16:43:01 [Bandis Testserver - Do what you want (PID: 9708)] Window Handle Found: 0x00000000000B0700
2017/02/19 16:46:20 [Bandis Testserver - Do what you want (PID: 9708)] Server Shutdown - Intiated by User when closing ConanServerUtility Script
2017/02/19 16:46:20 [Bandis Testserver - Do what you want (PID: 9708)] Server Window Found - Sending Ctrl+C for Clean Shutdown

**Comment by Dateranoth** [comment]
Maybe the INI configuration hadn't been pulled in. Hard to say. Glad it's working. Going to close this for now.
