### ISSUE TITLE
broadcast messages 

### ISSUE THREAD

**Issue by Mannot74** [Dateranoth/ConanExilesServerUtility#33]
Hello !

New patch note with : 

Added ability for server admin to broadcast messages to players on the server

i don't know how to use it, but perhaps you can use it for broadcast restart server / update / update mod ?

**Comment by Dateranoth** [comment]
I looked and it appears to be an in game option. If you hear of a way to do it from outside the game let me know, and I will implement it.

**Comment by Mannot74** [comment]
Ok thanks !
