### ISSUE TITLE
ModList

### ISSUE THREAD

**Issue by gabrielluis516** [Dateranoth/ConanExilesServerUtility#34]
Lots of issues using the mod update feature. It doesn't seem to be putting them in the order I specified and further, when I try rearranging the order in both the utility config ini and the modlist.txt, it seems to either overwrite it or ignore what I changed in the ini.

**Comment by gabrielluis516** [comment]
To add to this, in the ini file I currently have my modlist as "880454836,880177231,884956403"

Yet, it places mod 884956403 (ExpandedReligions.pak) at the top of the list!

**Comment by Dateranoth** [comment]
I will look into it, but off the top of my head I don't think it respects order. It does overwrite the mod list file. I will see what needs to be done to respect order.

**Comment by gabrielluis516** [comment]
Oooh, quick response! Thank you :)

I had thought you were mostly finished with this project. How does it determine which order to put them in?

**Comment by Dateranoth** [comment]
I am mostly done, but I do try to fix bugs.  I had to look, but it appears it should be alphabetically. The mods are listed by number, but Conan mod list wants the actual file name. To get that I am parsing the directory and adding the names I find to the list. 

I doubt I will be able to easily correct this, but I could make overwriting mod list optional. So you would have to update it manually.

**Comment by Dateranoth** [comment]
If you need to set the mod order, the easiest option looks to be to modify the modlist.txt then set it to read only. That should prevent my script from overwriting the file if you wish to set a particular order.  You will have to manually update the modlist when you add new mods.

**Comment by Dateranoth** [comment]
I have a plan for this that should work. It will require manual update to a file containing modIDs to mod files names the first time you run it if you're already using the script. I should be able to have it pushed out this weekend.

**Comment by Dateranoth** [comment]
There is a pre-release ready for beta testing. Best to try on a non production server.
https://github.com/Dateranoth/ConanExilesServerUtility/releases/tag/2.13.0-beta.1

**Comment by Dateranoth** [comment]
https://github.com/Dateranoth/ConanExilesServerUtility/releases/tag/2.15.0
The above release solves this problem.
