### ISSUE TITLE
I wasnt sure how to message you

### ISSUE THREAD

**Issue by Sixxgunz** [Dateranoth/ConanExilesServerUtility#41]
Took me a while to figure out the config file, but I love this tool.  I normally just use a batch file to handle server crashes, but have never had a stable way of auto restarts but since rcon came out and you already had discord built in and the remote restart option, this will be great, my admins are dying for this to kick in so they dont have to worry about restarts and logging in for announcements.  

Is there anyway you could add in an option to run a batch file after the server is shutdown/before the validate kicks in and possibly an extra 30 seconds on the delay in between?  I have set of scripts that I run in between each restart to keep up on server decay manually removing all inactive players and structures after a specific amount of days and if this were an option I don't think I would have much more to ask of you for writing this.

Thanks again!
SixxGunZ@WorldWarGaming.Net

**Comment by Dateranoth** [comment]
I don’t mind putting in the option to execute an external batch file before the steamcmd is ran or the server is started. I will program it to wait for the batch to finish executing. So any delay after your scripts run can be added by delaying the close of the batch file.

**Comment by Sixxgunz** [comment]
you're awesome thanks!

**Comment by Sixxgunz** [comment]
As an afterthought, I'm not sure if you ever considered this one, but would there be a way you could add two more functions / useable commands to your restart option.  A "Stop" and "Start" function for when you might need to stop the server safely, do any changes you may need to do since some config options sometimes need to be done during these times like, changing a server name after wiping, or in my case I sometimes do custom settings to the engine configs to boost server performance, or some config options that require the server to be down etc etc.  And then a way to send a "Start" option.  This way there would be no need to kill the autoit.exe process to do this.  Again dude, I've always been skeptical of your script, only because I've gotten so used to doing everything with myself or a capable admin present for restarts / updates etc, but this thing is just awesome, I'll be working all this into my 3 servers tonight finally, i can't wait to see peoples reactions, i'm such a nerd lol.

**Comment by Dateranoth** [comment]
I’m not exactly sure what you’re wanting.  You can safely stop the server now. If you right click on the icon in your system tray ( I use the icon from our site. A little grim reaper ) 

You can Pause the script. It will stop wherever it is at and not do anything else. 

You can Exit the script. This will prompt if you want to safely shut the server down. If you select yes it will close the server. No is so you can close the script, update any script INI settings or update the script without closing the server. It will remember the correct window and process and reattach to it when you open the script again. 

To start, just run the exe again. 

Oh, and be sure to check if the icon is flashing X when you’re done pausing it. If it is hat means it is still paused and script won’t process. 

I understand the nerd factor. Haha. I do enjoy updating a script for a game I don’t even play or host anymore.

**Comment by smooreace** [comment]
Im not getting the complexity either... I've literally NEVER had a need to stop the server for anything other than updates. If changes need to be made to the config, or startup .bat, then make the edits, save, and restart. There is literally ZERO need for the server to be offline while making changes!

**Comment by Dateranoth** [comment]
I believe he may not have realized you can cleanly stop the script without killing the process. It does get hidden if your system tray icons hide by default. 

The feature to leave the server running while closing the script is included so you can update the script INI, upgrade to the latest script version, or just stop using he script without restarting the server. You do have to close then reopen the script to change any of the script INI settings. 

Anyhow, I’m currently working on the option to execute an external script, batch file, or whatever. Should be done tonight.

**Comment by Dateranoth** [comment]
Feature Added in [3.2.0](https://github.com/Dateranoth/ConanExilesServerUtility/releases/tag/3.2.0)

Please open a new ticket if you have any further requests or problems! You can also reach me on Discord by the same user name. Enjoy!
