### ISSUE TITLE
TCP Error

### ISSUE THREAD

**Issue by 5tardu5t** [Dateranoth/ConanExilesServerUtility#45]
Getting error when launching the (ConanServerUtility_x64_v3.2.1.exe) - Could not bind IP [xxx.xxx.xxx.xxx] Check server IP or disable Remote Restart in INI. 
The server is being setup on a hosted dedicated server, and I have entered the servers correct and only IP address. I changed the ConanServerUtility.ini from BindIP=yes to BindIP=no, as the server only has 1 WAN IP address, so I can only assume I don't need the BindIP option enabled. Is the toggle for BindIP working correctly in the current release as it doesn't seem to register being turned off/toggled to no.
Thank you.

**Comment by Dateranoth** [comment]
Ok. This could be a couple of issues. Make sure the remote restart port is unique and not in use by any other application. It should be different from all other ports in the INI. 

The IP you are using should be the Servers local IP unless your server is directly connected to the internet with an outside IP. cmd>ipconfig . 

If that still doesn’t work try this: Set BindIP=no
Set IP in ini to 127.0.0.1
if still doesn’t work try setting it to 0.0.0.0

If that still doesn’t work then something on the machine is not allowing the application to open the remote restart port. Firewall, antivirus, etc. 

And I notice it is confusing, but the BindIP is for the Conan server not remote restart. It tells conan server to bind to the ip you set only or bind to all.

**Comment by 5tardu5t** [comment]
Dateranoth, thanks so much for the fast response. Tried all of it and was still getting stuck - firewall is off also and yes IP is directly connected. The port is definitely not being used, just chose a random port number, but thought what the hell, lets change it anyway, was something like (47001). Changed and started server straight away - no errors now. So no idea why it didn't like that port, but because of your reply it got me changing it and now i'm up and running. Cheers again ;)

**Comment by Dateranoth** [comment]
Hard to say why it didn’t like that port. Glad to help!
