### ISSUE TITLE
Steam running check not working

### ISSUE THREAD

**Issue by smooreace** [Dateranoth/ConanExilesServerUtility#47]
Since your latest update Ive had this a time or two. Seems to only happen with mod updates though. Not with my daily server restarts

https://gyazo.com/ca113d0f2b65af97fe31dfb98bd24cff

The check is enabled in the INI for both servers, and both are hung on restart

**Comment by Dateranoth** [comment]
This is a problem when you have steam open on the same machine you are running the server.

I already have an attempted fix built in to the script. It tries to close the error pop up when it sees it. It usually works, but sometimes it will miss the pop ups. 

Set SteamFix=yes

**Comment by smooreace** [comment]
Ya.. it seems to work fine on normal restarts. and game updates. But has failed every time on restarts related to mod updates.

**Comment by Dateranoth** [comment]
It must be coming up more than once. I can add some other checks. I will have to think and see if there is a better way to check for it. Is there any reason you have to run Steam on that machine?

**Comment by smooreace** [comment]
I dont know how you have that check implemented, obviously, but maybe delaying it some period of time, or longer, would do the job.

Having Steam running helps with server visibility for the 9 Ark servers running on that machine. they are already hard to find at times. Without Steam, they are almost always MIA.

**Comment by smooreace** [comment]
It's not a HUGE big deal to me... I get notifications if the servers are down for more than 60 seconds anyway. So it's not like I'm getting any real downtime from it most of the time. But people that run more mods will have far more potential for issues.

**Comment by Dateranoth** [comment]
Makes sense. I’ll see what I can do when I get back.

**Comment by Dateranoth** [comment]
When the error comes up, does the server window show the server name for a title or the path to the executable as a title?

**Comment by Dateranoth** [comment]
@smooreace This should take care of the problem. Give the latest release a go and let me know.

https://github.com/Dateranoth/ConanExilesServerUtility/releases/latest

**Comment by smooreace** [comment]
Sorry I didnt answer. Was going to tell you that this morning, for 2 servers, I had 9 steam popup errors to close to get the server to start. Not sure of what the processes are displaying when it happens. Will test the old version now to let you know.

**Comment by Dateranoth** [comment]
9? Dang. I wonder what’s different. I am currently checking for three per start, and I never saw more than two on my test rig. 

The next step would be to add it to a continuous check loop. Look for it every 5 minutes or so. 

Are they coming up one after another or do you get a long delay in between?

If this doesn’t work for you let me know and we will reopen. If you can get an idea of the maximum number of times it opens per server start and time in between, I can try to check for the max instances and add another check every 5 minutes or so just to be safe.

**Comment by smooreace** [comment]
There were 4 popups before the server process showed at all. I had to close 3, your script caught 1.

So after those 4 are closed ser server get to this point..
https://gyazo.com/31e6a8579442c7245ecb1828e164fad1

I closed ONE additional popup and one server moved forward, getting to this point...
https://gyazo.com/4d3846d8a13813849feb4afcf7dd936d
I THINK that server is live now. 

Still have at least one popup remaining...  clicking it gives me... another popup. Closing it brings... The second server to live status
https://gyazo.com/16f41d92da294e26cc3d217d07f8bfbd

And no more popups.

So both servers took a different number of manual popups to go live. Your script only caught 1

**Comment by smooreace** [comment]
Ill test the new script now.... give me a few minutes. I have contractors tearing out concrete ATM and I need to babysit

**Comment by smooreace** [comment]
It looks like that caught all of them. Both servers did their update chack and appear to be moving all the way to live status now. I only SAW 2 popups. The other had to have closed faster tha I could see

**Comment by smooreace** [comment]
Just as an FYI, I use Battlematrix.com to get notifications pushed to me for all of my 27 servers. Any time any of them are down for more than 10 minutes I get a text. VERY handy!!

Thanks for nailing this issue thought! Great work!

**Comment by Dateranoth** [comment]
Ok great! I do perform a while active loop on each iteration so it could hit multiple windows if they come up fast enough.  Keep an eye on it, but I will probably add a safety check to the next release just to make sure. Check for and close the window if it exists still after each 5 min check. 

I’ll have to check into that service.

**Comment by smooreace** [comment]
Great... Ill update here daily to let you know. My servers are only running Pippi. Not sure if mod count has anything to do with timing, or anything else.

**Comment by Dateranoth** [comment]
I don’t think that it does, but I hadn’t really researched it since pre release. When I first implemented it, it would appear twice then go away. I was thinking about it, and I can also make it configurable if necessary. 

So you could select how many windows you anticipate waiting for. 

I also wonder if it makes a difference if multiple servers restart at the same time. 

Regardless, I’m pretty sure what I have plus a check every 5 minutes will take care of it. 

I’m sure there is a better way, but this will work for now.

**Comment by smooreace** [comment]
For my morning restarts I have them offset by an hour. But mod updates end up hitting within a minute of each other.

**Comment by Dateranoth** [comment]
I need to look and see if I can determine window by primary process. I’ve been looking at C# and I know it’s possible through that, but I’m not sure about autoit. It should be, I just need to look into it a bit more. It wouldn’t be a problem at all as long as each utility is closing the window for its process. 

Still, as crazy as it is, it has done pretty well at supporting multiple servers.

**Comment by smooreace** [comment]
This morning I was met with..
https://gyazo.com/8a863e6bb056e6bb3a2aed2b3290d8b6

Yesterday in my testing I did a CTRL C to each server to shut them down. Tested twice and both times it worked fine. Now this morning its back to the same antics. Not sure what to tell ya!

I had to eventually close 4 popups total. 3 for the top server and 1 for the lower

**Comment by Dateranoth** [comment]
I’m on the road today. I’ll see if I can add the continuous check tonight.

**Comment by smooreace** [comment]
No problem. Just wanted to give you an update. Thanks

**Comment by Dateranoth** [comment]
Thanks for the updates. I’m not going to make the full trek today so I may not get to it. I’ll have something worked up by tomorrow night at least.

**Comment by smooreace** [comment]
Again... no biggy! Just getting you the info. What I have now is FAR more functional than having nothing at all!

**Comment by Dateranoth** [comment]
@smooreace 
This will finally work. I added a continuous check for the window. If steamfix is enabled, the utility will always look for that window and close it. It doesn't differentiate between servers, so one utility may close the window of another one, but I don't think it will be a problem.

https://github.com/Dateranoth/ConanExilesServerUtility/releases/tag/3.2.3

**Comment by smooreace** [comment]
Great... Didnt get a chance to test the last version. It seemed to act totally different if I killed the servers from when the script killed the servers for a restart. So I had to wait for a real scheduled reboot.

**Comment by smooreace** [comment]
OK... That latest update definitely took care of the steam popups.... but not until I brought the RDT window to the active window. RDP connection is always connected but minimized. As soon as I clicked it both Conan servers started buzzing along their load process. BattleMatrix confirms 1 and 2 hours downtime corresponding to the 1 hours separation in the servers restart time.

**Comment by Dateranoth** [comment]
That’s very strange. So, it worked, but not until you activated the RDP session?

If you check your logs, do your servers always say they had to be killed and did not shut down gracefully?

I’m beginning to think that your system blocking the script actions when RDP is minimized. AutoIT relies on emulated key presses. So, I’m wondering if the system disables something if it can still perform the function. 


Ok. A quick search does reveal what is going on. Seems to be an RDP feature for bandwidth reduction. 

The link below gives instructions on how to disable this on your local PC. Hopefully it will work. 

http://www.networkautomation.com/urc/knowledgebase/running-interactive-tasks-in-minimized-remote-desktop-windows/4ecdf43e03470/

**Comment by smooreace** [comment]
That makes perfect sense. And explains some of the tests that have strangely been successful while others failed. It all depended on my being busy with other things or not. I run through the link... I was missing this one      HKEY_CURRENT_USER\Software\Wow6432Node\Microsoft\Terminal Server Client

Created it and the DWORD entry. Not sure if it will actually work or not. Ive done a lot of registry work, but never created anything that high up the food chain. Testing now

**Comment by smooreace** [comment]
First test failed. But I didnt restart the RDP session. Restarted both servers again and killed the RDP session. Servers hung, I assume waiting for a window to be closed.
Opened the RDP session and it had 2 popups open... but both in the background. So your script wasnt seeing them to close them. As soon as I made the popup the active window it closed and moved on.

Shut down both servers again and minimized the RDP session. (wish there was a way to monitor it without it being open!) But it still seems to be hanging, waiting for a click. So Im guessing that the registry key I added didnt take.

**Comment by smooreace** [comment]
The easiest solution is probably to leave the RDP session as the active window when I crash at night, and adjust my restart times so Im awake. Just in case there is an issue. Thanks for all your work on this!!

**Comment by Dateranoth** [comment]
Yeah, or grab a RDP manager and just close the RDP sessions. 

Here is another registry instruction. One might have been for 64/32 bit. 

https://robot.uipath.com/docs/executing-tasks-in-a-minimized-rdp-window

Glad to help!

**Comment by smooreace** [comment]
I never messed with an RDP manager because I just deal with 3. But that seems to have solved everything.

**Comment by Dateranoth** [comment]
Fantastic! Let me know if you need anything else. I have a few features I want to add in now that the bug hunts are dying down.

**Comment by smooreace** [comment]
Several days in and still working great. Thanks again for your help!

**Comment by Dateranoth** [comment]
Glad to help!
