### ISSUE TITLE
Running from Asus ROG RamDisk

### ISSUE THREAD

**Issue by FightzGamer** [Dateranoth/ConanExilesServerUtility#48]
Hello,

So i love this utility but i ran in to a strange problem. I have moved my Conan server to a Ramdisk, to get max performance out of it. I works like a dream when i start the server with the normal .bat file.

However, when i try to run the server with the Utility it gets stuck right before the server open up and just stalls the conan server. The icon is also missing in the task manger of my windows server, so i think there might be a bug with the utility.

I know that using a ramdisk is a different setup then normal, but it should work. I have tried running the utility form the C: and from the ramdisk it self. It did not change anything.

I'm using this software for the ramdisk: https://rog.asus.com/tag/rog-ramdisk/
It works with everything else :-P Building load times are amazing with this! :-)

**Comment by Dateranoth** [comment]
Can you send me your log files from the utility after it stalls, your INI settings as well? 

Does steamcmd finish running before it hangs?

**Comment by FightzGamer** [comment]
Yeah, steamcmd runs first and finishes then it loads the server console and stalls at the end of that.

[ConanServer1_Ramdisk_test.zip](https://github.com/Dateranoth/ConanExilesServerUtility/files/2105232/ConanServer1_Ramdisk_test.zip)

I have also send you the conan server log, i was able to do the ctrl+c to shut it down. I'm wondering why i could do that, when the server was stalled.. It might be running but just not opening the port.. This is a strange bug to me..

Thanks for trying to help with this. If you think it's not the Utility at fault here, then please say so.. I will try to figure out what could be wrong with the setup.

**Comment by Dateranoth** [comment]
I’m not sure. The utility gets everything to the point that it starts the server and logs the window handle. It’s possible that it’s a permission problem. Did you copy the server over or did you let the utility use steamcmd to download a new copy?

If not then try clearing the ram disk storage and starting with a fresh install with basic settings. 

I will run some tests with the RAM disk tonight to see if I can replicate the problem.

**Comment by FightzGamer** [comment]
Okay, thanks for helping.

This is the download link for the Asus ROG Ramdisk download. http://dlcdnet.asus.com/pub/ASUS/mb/Utility/RAMCACHE_II_Win10_V10506_20170822.zip

They call it Ersion RAMCACHE 2 for some reason.. took for ever to find the download link again. 

All you have to do is to install it, restart and then make a drive. Just make sure to give it enough space, 8 Gb should be fine. Then you point the "Junction" at the path of the Conan server and it will copy the files. After that just start the server as you normally do with the Utility :-) 

Do not put stuff on the ram drive it self. It will not save changes if you do. Talking form experience here :'(
It's a little different the other ram drives i have seen. I started with installing directly on the ram drive it self, that was the wrong way of doing it..

**Comment by Dateranoth** [comment]
I don't have the proper hardware apparently, so I can't test it. Sorry.  Can you start the ram cache from a command line? If so, you might try using launch external app feature of the utility to start it right before the server starts. I'm wondering if the utility is modifying something it shouldn't for the ramcache before the game actually launches.  Alternatively, you could try disabling everything in the utility except the actually launching of the game and see if that works.

**Comment by smooreace** [comment]
Im betting it has a lot to do with this... "Do not put stuff on the ram drive it self. It will not save changes if you do."

If the server is running from the RAM drive, the utility should be looking to the executable running from that RAM drive to verify that its running, and react accordingly. If you cant actually access the RAM drive directly then you will never successfully get an automatic update to happen, and you will never get a mod update to happen. When either is triggered the whole thing will crash on itself. And how is the server supposed to function if it cant write changes?

**Comment by FightzGamer** [comment]
I have found the issue, it was the file rights on the ram drive.

You where absolutely right about rights not being set correctly. 

yes, you need to use the junction and not put files on the drive. I learned that the hard way.

This issue is fixed. thanks for the help :-)

**Comment by Dateranoth** [comment]
Glad you figured it out! Let me know if any other problems come up.
