### ISSUE TITLE
New Daily/Hourly Restart issue

### ISSUE THREAD

**Issue by smooreace** [Dateranoth/ConanExilesServerUtility#49]
The new restarts options aren't taking properly. It's not a big deal particularly. Both of my servers restarted, then warned everyone, and came back up fine. Just didn't follow the rules I created... unless Im a total retard and did something stupid that I cant see.

https://gyazo.com/07d032686bf65fdf5d0f66a7b1eef8be

https://gyazo.com/65d1623d5a0f7d8e2bf90c74a77c8349

**Comment by Dateranoth** [comment]
Hmm. Can you send me the log for those times? Also, are you running beta.2? I had a bug in .1 

Your server is running in the same time zone right?

**Comment by Dateranoth** [comment]
Actually, neither one of those should have restarted today. You don’t have Tuesday selected for either one. 

Unless you’re way ahead of me, and even then only one would have restarted.

**Comment by smooreace** [comment]
Im in Kansas... no clue where you are. And yes.. they are on the same machine. Gathering logs now.

**Comment by smooreace** [comment]
Just realized that it might have been the Conan update that did it.

**Comment by smooreace** [comment]
Thats exactly what it was... sorry!
```
`2018/06/19 08:08:08 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 11552)] Server is Out of Date! Installed Version: 2865501 Latest Version: 2874666
2018/06/19 08:08:08 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 11552)] Bot in Use. Delaying Shutdown for 5 minutes. Notifying Channel
2018/06/19 08:08:10 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 11552)] [RCON] Sent ( The Tropolis Collective 5xAll -RPLite-[PVP] Restarting in 5 minutes ) to Players
2018/06/19 08:08:10 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 11552)] [Discord Bot] Message Status Code {200} Enable Debugging to See Full Response Message
2018/06/19 08:12:12 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 11552)] [RCON] Sent ( The Tropolis Collective 5xAll -RPLite-[PVP] Restarting in 1 minute. Final Warning ) to Players
2018/06/19 08:12:12 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 11552)] [Discord Bot] Message Status Code {200} Enable Debugging to See Full Response Message
2018/06/19 08:13:11 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 11552)] Server Window Found - Sending Ctrl+C for Clean Shutdown
2018/06/19 08:14:11 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 11552)] Server Did not Shut Down Properly. Killing Process
2018/06/19 08:14:15 Running SteamCMD without validate. [steamcmd.exe +@ShutdownOnFailedCommand 1 +@NoPromptForPassword 1 +login anonymous +force_install_dir E:\Game Server\Conan\conan pvp +app_update 443030 +quit]
2018/06/19 08:15:27 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 7072)] Started [ConanSandboxServer-Win64-Test.exe ConanSandBox -MULTIHOME=10.182.207.201 -Port=7792 -QueryPort=27072 -RconEnabled=1`
```

**Comment by smooreace** [comment]
Wow... that pasted TERRIBLY!

**Comment by Dateranoth** [comment]
Haha. Yes it did. Let me know if it restarts tomorrow when it should. In KY btw.

**Comment by smooreace** [comment]
OK... the PVE server is trying to restart now... Its currently midnight on the 20th.  Heres the config

[Restart Server Daily? yes/no]
RestartDaily=yes
[Daily Restart Hours Comma Seperated 0=Everyday Sunday=1 Saturday=7 0-7]
RestartDays=1,4
[Daily Restart Hours Comma Seperated 00-23]
RestartHours=4
[Daily Restart Minute 00-59]
RestartMinute=00

And the log entry

Bot in Use. Delaying Shutdown for 5 minutes. Notifying Channel
2018/06/20 00:00:02 [The Tropolis Collective 2.5xAll RP Lite[PVE] (PID: 9968)] [RCON] Sent ( The Tropolis Collective 2.5xAll RP Lite[PVE] Restarting in 5 minutes ) to Players
2018/06/20 00:00:02 [The Tropolis Collective 2.5xAll RP Lite[PVE] (PID: 9968)] [Discord Bot] Message Status Code {200} Enable Debugging to See Full Response Message
2018/06/20 00:04:04 [The Tropolis Collective 2.5xAll RP Lite[PVE] (PID: 9968)] [RCON] Sent ( The Tropolis Collective 2.5xAll RP Lite[PVE] Restarting in 1 minute. Final Warning ) to Players
2018/06/20 00:04:04 [The Tropolis Collective 2.5xAll RP Lite[PVE] (PID: 9968)] [Discord Bot] Message Status Code {200} Enable Debugging to See Full Response Message
2018/06/20 00:05:03 [The Tropolis Collective 2.5xAll RP Lite[PVE] (PID: 9968)] Server Window Found - Sending Ctrl+C for Clean Shutdown

**Comment by smooreace** [comment]
So basically its ignoring the hour setting.

**Comment by Dateranoth** [comment]
Bleh. I think I see what it is, but I need to run a test or two. It may still restart at 4 as well. It hadn’t tried to restart every hour has it? I’ll try and get it fixed tomorrow.

**Comment by smooreace** [comment]
No biggy! I was just letting you know.

**Comment by smooreace** [comment]
Another update... Restarts are stupid! The config settings are above. This is the PVP server BTW
https://gyazo.com/5e8da033069cbd15cbcd0c72284d8310
Log entry pertaining to the restart

> 2018/06/22 00:00:00 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 7072)] Work Memory:2714955776 Peak Memory:4093079552 - Daily Restart Requested by ConanServerUtility Script
2018/06/22 00:00:00 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 7072)] Bot in Use. Delaying Shutdown for 5 minutes. Notifying Channel
2018/06/22 00:00:01 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 7072)] [RCON] Sent ( The Tropolis Collective 5xAll -RPLite-[PVP] Restarting in 5 minutes ) to Players
2018/06/22 00:00:02 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 7072)] [Discord Bot] Message Status Code {200} Enable Debugging to See Full Response Message
2018/06/22 00:04:04 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 7072)] [RCON] Sent ( The Tropolis Collective 5xAll -RPLite-[PVP] Restarting in 1 minute. Final Warning ) to Players
2018/06/22 00:04:04 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 7072)] [Discord Bot] Message Status Code {200} Enable Debugging to See Full Response Message
2018/06/22 00:05:03 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 7072)] Server Window Found - Sending Ctrl+C for Clean Shutdown
2018/06/22 00:06:03 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 7072)] Server Did not Shut Down Properly. Killing Process
2018/06/22 00:06:06 Running SteamCMD without validate. [steamcmd.exe +@ShutdownOnFailedCommand 1 +@NoPromptForPassword 1 +login anonymous +force_install_dir E:\Game Server\Conan\conan pvp +app_update 443030 +quit]
2018/06/22 00:06:19 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 12596)] Started [ConanSandboxServer-Win64-Test.exe ConanSandBox -MULTIHOME=10.182.207.201 -Port=7792 -QueryPort=27072 -RconEnabled=1 -RconPassword=***6int******* -RconPort=32381 -MaxPlayers=50 -ServerName="The Tropolis Collective 5xAll -RPLite-[PVP]" -listen -nosteamclient -game -server -log]
2018/06/22 00:06:37 [The Tropolis Collective 5xAll -RPLite-[PVP] (PID: 12596)] Window Handle Found: 0x0000000027A904CE >

**Comment by Dateranoth** [comment]
Yeah, it’s definitely broke right now. You can roll back to the last full release if you need it. I still think I know what it is, but I’ve been so busy I haven’t had time to sit down and fix it. Yesterday was a 16 hour day at work alone. 

I will try to get to it by this weekend. Thanks for the update!

**Comment by smooreace** [comment]
It's not a problem... the great thing is that it's still updating like it needs to, and restarts are at a safe time. Just cant guess as to what days they might happen.

**Comment by Dateranoth** [comment]
I finally got around to working on this. This version should work.
https://github.com/Dateranoth/ConanExilesServerUtility/releases/tag/3.3.0-beta.3

**Comment by smooreace** [comment]
That did the trick! Thanks again for the work!

**Comment by Dateranoth** [comment]
No problem! Would go a lot better if I would get it right the first time. Haha. I’ll push it out of beta when I can.
