### ISSUE TITLE
A new shutdown bug

### ISSUE THREAD

**Issue by smooreace** [Dateranoth/ConanExilesServerUtility#51]
This one seems to have been triggered by the server update or in some way related to an internet outage. 

Ititial windows I woke up to
https://gyazo.com/6eb998d3cf4b1c83e3031ea61866e5ea

And after hitting OK I got this.
https://gyazo.com/6c3c323704d4662189d5e2e31a4b7899

After that everything seems to be running fine

**Comment by smooreace** [comment]
I lied... servers shut down as I expected, but never came back up. It appears that the first OK selection shut down your utility

**Comment by Dateranoth** [comment]
Can you send me your log file? Is it working correctly now?

On Aug 2, 2018, at 10:27 AM, smooreace <notifications@github.com<mailto:notifications@github.com>> wrote:


I lied... servers shut down as I expected, but never came back up. It appears that the first OK selection shut down your utility

**Comment by smooreace** [comment]
Here is that part of the log..

https://pastebin.com/G1QpPygk

**Comment by smooreace** [comment]
And yes... It ran fine once I continued past it. Wont know if its a repeat issue until I get another game/mod update

**Comment by Dateranoth** [comment]
I’m trying to determine if it was a fluke or not. It is most likely how I am checking for updates. I have to parse through the text and I’m using array splits. I thought I was checking to make sure the array was valid, but I might have missed a check. If the information downloaded properly it shouldn’t happen. I’m thinking maybe something changed or went wrong on the mod side.

Let me know if it happens again. I’m pretty swamped at work, and won’t have time to test until next weekend at the earliest.

On Aug 2, 2018, at 11:43 PM, smooreace <notifications@github.com<mailto:notifications@github.com>> wrote:


And yes... It ran fine once I continued past it. Wont know if its a repeat issue until I get another game/mod update

**Comment by smooreace** [comment]
No problem... totally understand! As always, just trying to get you info, NOT complain! Even if this only worked 50% of the time it would be a 50% reduction in MY workload! So a crash from time to time is definitely not hurting anything. 

My only mod was updated last on the 27th, so it was definitely the game update that triggered the issue. 

Thanks for the great work!!

**Comment by Dateranoth** [comment]
That helps. I can look into the update code this way. My best guess is the file wasn’t downloaded from steam command properly, and then it tried to parse something that wasn’t there. I’ll take a look when I can. Just keep me posted if the next update works or not. Thanks!

On Aug 3, 2018, at 8:02 AM, smooreace <notifications@github.com<mailto:notifications@github.com>> wrote:


No problem... totally understand! As always, just trying to get you info, NOT complain! Even if this only worked 50% of the time it would be a 50% reduction in MY workload! So a crash from time to time is definitely not hurting anything.

My only mod was updated last on the 27th, so it was definitely the game update that triggered the issue.

Thanks for the great work!!

**Comment by smooreace** [comment]
Just another update... 

Conan update last night/this morning went fine. Servers updated as needed and came back up perfectly. Maybe the issue was just a fluke.

**Comment by Dateranoth** [comment]
I’m guessing it was something that went wrong downloading the update information. I  thought I was checking for empty arrays properly, but I probably missed something. Hopefully it was just a fluke.

On Aug 13, 2018, at 11:52 AM, smooreace <notifications@github.com<mailto:notifications@github.com>> wrote:


Just another update...

Conan update last night/this morning went fine. Servers updated as needed and came back up perfectly. Maybe the issue was just a fluke.
