### ISSUE TITLE
Any way to have this work on a rented server?

### ISSUE THREAD

**Issue by chinagreenelvis** [Dateranoth/ConanExilesServerUtility#52]
I'm leasing a Conan Exiles server from G-Portal. Most of the operations are done through their web interface, but I also have FTP access. Is there a way to get this utility functioning for it? I'm particularly interested in the mod-updating feature.

**Comment by Dateranoth** [comment]
Not unless G-Portal admins allow you to run a different executable on server start or access the machine directly.  You would need to contact them to confirm. I thought some of their games supported automatic mod updates. May be worth requesting to them.



On Apr 4, 2020, at 7:26 PM, chinagreenelvis <notifications@github.com> wrote:

﻿

I'm leasing a Conan Exiles server from G-Portal. Most of the operations are done through their web interface, but I also have FTP access. Is there a way to get this utility functioning for it? I'm particularly interested in the mod-updating feature.
