### ISSUE TITLE
Mod error detection?

### ISSUE THREAD

**Issue by chinagreenelvis** [Dateranoth/ConanExilesServerUtility#53]
So I'm looking more and more to migrating to a local server and using this, but my latest problem with my rented server turned out to be an issue with a mod that was updated; Savage Steel was screwed up by an update and refused to load. Problem is that the server still restarted, only without the mod, which caused items that had been placed on top of Savage Steel assets to be destroyed.

Can this system be made to prevent the server from starting if a mod update breaks it? Or to create a specific save-game backup prior to restarting due to a mod update?

**Comment by Dateranoth** [comment]
First. I would suggest downloading it and testing it. I have not updated it in a long time, and I do not currently use it. It should still work, but updates to Conan could have broken it.  I will support it where I can, and try to fix it, but I haven't had a lot of time to do so.

With that said, there is no built in way for me to know that a mod did not load. There is also no built in save feature.  However, there is a built in feature that allows you to run a custom script before starting the server. You could use this to call a batch file or something similar to backup your server directory.

**Comment by chinagreenelvis** [comment]
Wrote an AHK script that backs up the save on restart. Works great.

**Comment by Dateranoth** [comment]
Awesome. Glad you were able to make it fit your needs.
