### ISSUE TITLE
Where is the exe file ?

### ISSUE THREAD

**Issue by Mannot74** [Dateranoth/ConanExilesServerUtility#7]
Hello, Sorry but where is the exe file ?

**Comment by Dateranoth** [comment]
It's in the zip included with the latest release. https://gmcd.me/conanutilrelease

Choose either 64 bit or 32 bit. Latest full releases will always be at the above link.

On Feb 11, 2017, at 12:02 AM, Mannot74 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, Sorry but where is the exe file ?

**Comment by Dateranoth** [comment]
https://github.com/Dateranoth/ConanExilesServerUtility/releases/latest

That contains the latest compiled release.
