### ISSUE TITLE
Crash after some time

### ISSUE THREAD

**Issue by chrisraiden** [Dateranoth/ConanExilesServerUtility#8]
I get a AutoIT Error
Line: 7553
The requested action with this object has failed

This error comes after some time .. after press OK .. it ask me to shutdown the server with yes/no

My Config File
[Use MULTIHOME to Bind IP? Disable if having connection issues (yes/no)]
BindIP=yes
[Game Server IP]
ListenIP=X.X.X.X.X
[Game Server Port]
GamePort=7777
[Steam Query Port]
QueryPort=27015
[Server Name]
ServerName=DE ConanExiles.Zone RP
[Server Password]
ServerPass=5678
[Admin Password]
AdminPass=1234
[Max Players]
MaxPlayers=60
[Server Directory. NO TRAILING SLASH]
serverdir=C:\conanrp
[Use SteamCMD To Update Server? yes/no]
UseSteamCMD=yes
[SteamCMD Directory. NO TRAILING SLASH]
steamcmddir=C:\SteamCMD
[Validate Files Every Time SteamCMD Runs? yes/no]
validategame=no
[Use Remote Restart ?yes/no]
UseRemoteRestart=no
[Remote Restart Port]
ListenPort=57520
[Remote Restart Password]
RestartCode=FVtb2DXgp8SYwj7J
[Restart Server Daily? yes/no]
RestartDaily=no
[Check for Update Every X Minutes? yes/no]
CheckForUpdate=yes
[Update Check Interval in Minutes 05-59]
UpdateInterval=30
[Daily Restart Hours? 00-23]
HotHour1=00
HotHour2=06
HotHour3=12
HotHour4=18
HotHour5=00
HotHour6=00
[Daily Restart Minute? 00-59]
HotMin=00
[Excessive Memory Amount?]
ExMem=6000000000
[Restart On Excessive Memory Use? yes/no]
ExMemRestart=no
[Running Server with Steam Open? (yes/no)]
SteamFix=no
[Rotate X Number of Logs every X Hours? yes/no]
logRotate=yes
logQuantity=10
logHoursBetweenRotate=24

**Comment by Dateranoth** [comment]
Been in contact and we believe we have found the issue. Not directly related to the code, but I am adding some additional checks just to make it a bit less likely to crash.
